### PR TITLE
Fixed the problem that the rocket could not carry player

### LINKED ISSUE #74: Rocket launching without taking the players with it
## Description (Required)

After setting up the rocket with its launchpad, you choose the destination and you type in the coordinates.
Then after 5 messages, it should bring any entities within 5 blocks to the destination.
But unless you're not OP, the rocket doesn't bring you to the destination.

So I think there may be some tweaking to do on your end since there are only Slimefun and Galactifun installed

## Steps to reproduce the Issue (Required)
Download papermc 1.17.1 and set up local server
Install just Slimefun and Galactifun

## Expected behavior (Required)
Bring the players with it to the destination

## Server Log / Error Report

Only errors I see is here but I believe this is from due to hosting from local and has no issue with running Slimefun
https://pastebin.com/DyEWcYTN

## Environment (Required)

Screenshot 2021-09-24 183335

### PR DESCRIPTION
**Pull request by zimzaza4**
## Changes

Add metadata to the player before transferring players

## Related Issues

Resolves #74

## Checklist

+ [x] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

**Review by Seggan — APPROVED** [review]
LGTM but I'd wait for another review by someone else

**Comment by Seggan** [comment]
Also was this tested?

**Comment by zimzaza4** [comment]
Oh, i will test it

File: src/main/java/io/github/addoncommunity/galactifun/api/items/Rocket.java [hunk 1]
```diff
@@ -231,6 +232,9 @@ public void run() {
                 if ((entity instanceof LivingEntity && !(entity instanceof ArmorStand)) || entity instanceof Item) {
```
Comment (ProfElements) [inline src/main/java/io/github/addoncommunity/galactifun/api/items/Rocket.java:232]: Can the `instanceof Player` not just be included in this since we dont care about any other mobs being teleported?

Comment (zimzaza4) [reply src/main/java/io/github/addoncommunity/galactifun/api/items/Rocket.java:232]: Umm...worldManager only prevents players from teleporting to other worlds

**Comment by zimzaza4** [comment]
The test is complete, the Issue has been resolved

**Comment by zimzaza4** [comment]
when will this PR merged?

**Comment by ProfElements** [comment]
LGTM
